### ISSUE TITLE
某些浏览器中打开“报账人门户”或者“审批人门户”页面，“我要填单”/“未完成”/“已完成”，没有显示

### ISSUE THREAD

**Issue by xxd3vin** [xxd3vin/bgy-portalbillquery#3]
某些浏览器中打开“报账人门户”或者“审批人门户”页面，“我要填单”/“未完成”/“已完成”，没有显示

menzhen: 偶发出现，打开报账人门户或审批人门户，“我要填单”，“未完成”，“已完成”页签消失，同时发现未完成的数量一直是39，这个问题，可能与后台整合了三个页签到一个div中，通过ReactJS渲染，未加载成功有关。

![insertpic_](https://cloud.githubusercontent.com/assets/5204106/21916811/f2421af8-d97d-11e6-9c02-aeae98da169e.jpg)

**Comment by xxd3vin** [comment]
在远程碧桂园的电脑时候，复现了该问题，IE11。

但是当使用F12打开调试窗口，然后F5刷新之后，“我要填单”等标签页又显示出来了，即使关闭了IE的调试窗口，问题仍然没有出现。所以不确定这个什么原因引起的。

**Comment by menzhen** [comment]
后台代码中，我发现你将我要填单，未完成，已完成三个页签整合到了一个div内，通过reactJS去渲染，那么这个div如果没有加载出来，就和出现的问题效果一样

**Comment by xxd3vin** [comment]
你指的“div没有加载出来”的意思是Java没有拼接出HTML字符串还是ReactJS没有渲染出DOM节点？

**Comment by xxd3vin** [comment]
原因在js缓存上，最新版是0.37.3，但是HTML引用js时候：

```
<script src="/iwebap/js/portalbillquery/MyExpBillPortlet.js?v=0.22"></script>
```

直接通过浏览器查看`http://.../iwebap/js/portalbillquery/MyExpBillPortlet.js?v=0.22`的时候，发现文件头中的版本仍然是`0.22`。

但是目前暂时不能确定是浏览器缓存还是服务器端缓存。

已经通过修改querystring中的版本号来解决了。
